export default () => {
  return [
    {
      title: "Burger",
      method:
        "Beef patty. Buns. Tomatoes. Onions Cheesee Latus Method: Fry the beef patties until brown",
      imageUri: require("../../assets/burger.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
    {
      title: "Ice Cream",
      method: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/ice_cream.jpg"),
      name: "Brenda White",
      userImage: require("../../assets/girl2.jpeg"),
    },
    {
      title: "Maccaroni",
      method: "R 100",
      imageUri: require("../../assets/maccaroni.jpg"),
      name: "Anthony Richards",
      userImage: require("../../assets/guy.jpeg"),
    },
    {
      title: "Meat Balls",
      method: "R 100",
      imageUri: require("../../assets/meat_ball.jpg"),
      name: "Boby Farm",
      userImage: require("../../assets/guyw2.jpeg"),
    },
    {
      title: "Pasta",
      method: "R 100",
      imageUri: require("../../assets/pasta.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Fish",
      method: "R 100",
      imageUri: require("../../assets/fish.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Avocado Salad",
      method: "R 100",
      imageUri: require("../../assets/avo_salad.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
    {
      title: "Pancakes",
      method: "R 100",
      imageUri: require("../../assets/pancakes.jpg"),
      name: "Brenda White",
      userImage: require("../../assets/girl2.jpeg"),
    },
    {
      title: "Green Salad",
      method: "R 100",
      imageUri: require("../../assets/vegan_salad.jpg"),
      name: "Anthony Richards",
      userImage: require("../../assets/guy.jpeg"),
    },
    {
      title: "Beef Steak",
      method: "R 100",
      imageUri: require("../../assets/steak.jpg"),
      name: "Boby Farm",
      userImage: require("../../assets/guyw2.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      imageUri: require("../../assets/tomato_salad.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      imageUri: require("../../assets/veg.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Ribs",
      method: "R 100",
      imageUri: require("../../assets/ribs.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
    {
      title: "Dessert",
      method: "R 100",
      imageUri: require("../../assets/chocolate.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      imageUri: require("../../assets/mixed_salad.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Dessert",
      method: "R 100",
      imageUri: require("../../assets/brownies.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      imageUri: require("../../assets/chessee_salad.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Breakfast",
      method: "R 100",
      imageUri: require("../../assets/break_fast.jpg"),
      name: "Boby Farm",
      userImage: require("../../assets/guyw2.jpeg"),
    },
    {
      title: "Pasta",
      method: "R 100",
      imageUri: require("../../assets/past_olive.jpg"),
      name: "Anthony Richards",
      userImage: require("../../assets/guy.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      imageUri: require("../../assets/salad_sm.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
  ];
};
