export default () => {
  return [
    {
      title: "Burger",
      ingredients: "Beef patty, Buns, Tomatoes, Onions, Cheesee, Latus",
      method:
        "Fry the beef patties until brown. Butter the buns, Place 1 leaf of lettus, fried patties and chessee slices",
      imageUri: require("../../assets/burger.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
    {
      title: "Ice Cream",
      method:
        "Add milk, cream and sugar to iceam machine, add egg yolk and turn it on. refrigirate overnite",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/ice_cream.jpg"),
      name: "Brenda White",
      userImage: require("../../assets/girl2.jpeg"),
    },
    {
      title: "Maccaroni",
      method:
        "Boil Maccaroni until soft. bring milk to boil, add cheessee, salt, spice and cook on low heat. Add the maccaroni",
      ingredients: "1 pack of Maccaroni, salt, chessee, spice, cooking oil",
      imageUri: require("../../assets/maccaroni.jpg"),
      name: "Anthony Richards",
      userImage: require("../../assets/guy.jpeg"),
    },
    {
      title: "Meat Balls",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/meat_ball.jpg"),
      name: "Boby Farm",
      userImage: require("../../assets/guyw2.jpeg"),
    },
    {
      title: "Pasta",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/pasta.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Fish",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/fish.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Avocado Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/avo_salad.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
    {
      title: "Pancakes",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/pancakes.jpg"),
      name: "Brenda White",
      userImage: require("../../assets/girl2.jpeg"),
    },
    {
      title: "Green Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/vegan_salad.jpg"),
      name: "Anthony Richards",
      userImage: require("../../assets/guy.jpeg"),
    },
    {
      title: "Beef Steak",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/steak.jpg"),
      name: "Boby Farm",
      userImage: require("../../assets/guyw2.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/tomato_salad.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/veg.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Ribs",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/ribs.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
    {
      title: "Dessert",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/chocolate.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/mixed_salad.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Dessert",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/brownies.jpg"),
      name: "Bongiwe Moloi",
      userImage: require("../../assets/straightBack.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/chessee_salad.jpg"),
      name: "Nomsa Ntuli",
      userImage: require("../../assets/b_girl.jpeg"),
    },
    {
      title: "Breakfast",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/break_fast.jpg"),
      name: "Boby Farm",
      userImage: require("../../assets/guyw2.jpeg"),
    },
    {
      title: "Pasta",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/past_olive.jpg"),
      name: "Anthony Richards",
      userImage: require("../../assets/guy.jpeg"),
    },
    {
      title: "Salad",
      method: "R 100",
      ingredients: " 2L Milk, Sugar, 2L Cream",
      imageUri: require("../../assets/salad_sm.jpg"),
      name: "Sarah Smith",
      userImage: require("../../assets/girl.jpeg"),
    },
  ];
};
